@host = http://localhost:5003

### Get all tasks
GET {{host}}/tasks

### Get task by id
GET {{host}}/tasks/1

### Create task
POST {{host}}/tasks
Content-Type: application/json

{
  "title": "Learn backend",
  "status": "Later"
}